### PR TITLE
Fix project root

### PR DESCRIPTION
**Pull request by a7ex**
If you use xcresultparser to export xml for sonarqube (`xcresultparser -o xml <path-to-xcresult-bundle>`) please test this PR, whether it breaks anything on your side. Only the pathnames of the Test Classes should be affected and only, if a `project-root` is provided in order to map the classes to filenames.

Instead of grep-ing for each class name the whole directory provided in `project-root` xcresultparser now builds file index beforehand now by using only one egrep call and uses it as lookup table for filenames of test classnames. Improvement by an order of magnitude. Large xcresult bundle which ran for minutes before now run in seconds...! DUH, that was very bad before ;-(

### CODE REVIEW

**Comment by a7ex** [comment]
Yes, I would definitely like to be able to avoid this naive search through all files to match test classnames to files, where the classes are defined. Not exactly sure how and whether it's worth the hassle.

**Review by DanielBarberaDimoftache-TomTom — COMMENTED** [review]
It's flying. The project I tested it on has 7577 Swift files and 224 ObjC files (assuming I know how to count), and the result bundles are ~70 MB large. File matching is working well and accurately.
```
xcresultparser -o xml --project-root $(pwd -P)  2.07s user 1.25s system 61% cpu 5.375 total
```

**Comment by DanielBarberaDimoftache-TomTom** [comment]
> Yes, I would definitely like to be able to avoid this naive search through all files to match test classnames to files, where the classes are defined. Not exactly sure how and whether it's worth the hassle.

A good place to start might be [SourceKitten](https://github.com/jpsim/SourceKitten)! But you named it, perhaps it's not worth the hassle for this specific edge case.

**Comment by DanielBarberaDimoftache-TomTom** [comment]
@a7ex Heyo! I've been tinkering with this for a couple days for one of our projects, and noticed a couple of edge cases:
* ObjC++ is not supported, meaning that the path won't be relative to the project root. Fix is as easy as adding `--include *.mm` to the `egrep` command -- tested it myself, but perhaps it's a non-goal of the tool?
* When there's two (or more?) test classes with the same name, in test files with the same name, the `path` will be the same for both entries. (0.01% of our tests, so a literal edge case for us. :P)

As always, thanks for the amazing work, and kind regards!

**Pull request merged**
